# Generated by Django 5.0.6 on 2024-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hi', max_length=20, verbose_name='Первый столбец')),
                ('text', models.CharField(default='about', max_length=30, verbose_name='Второй столбец')),
            ],
        ),
    ]
